export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_ONE_MOVIE_SUCCESS = 'SEARCH_ONE_MOVIE_SUCCESS';
export const SEARCH_ONE_MOVIE_ERROR = 'SEARCH_ONE_MOVIE_ERROR';
export const RESET_DETAILED_MOVIE = 'RESET_DETAILED_MOVIE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
